name: Android CI

on:
  push:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-android

      - run: ./gradlew lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-android

      - run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-android

      - run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
      - run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/setup-android
#      - uses: google-github-actions/auth@v2
#        with:
#          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
#
#      - run: |
#          npx firebase-tools appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
#          --app ${{ secrets.APP_ID }} \
#          --groups "testers" \
#          --release-notes "Build automático via CI"

